
package com.zh.oukele.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServerIService", targetNamespace = "http://server.oukele.zh.com", wsdlLocation = "http://localhost:8080/CXFServer_war/ws/webServer?wsdl")
public class WebServerIService
    extends Service
{

    private final static URL WEBSERVERISERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVERISERVICE_EXCEPTION;
    private final static QName WEBSERVERISERVICE_QNAME = new QName("http://server.oukele.zh.com", "WebServerIService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/CXFServer_war/ws/webServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVERISERVICE_WSDL_LOCATION = url;
        WEBSERVERISERVICE_EXCEPTION = e;
    }

    public WebServerIService() {
        super(__getWsdlLocation(), WEBSERVERISERVICE_QNAME);
    }

    public WebServerIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVERISERVICE_QNAME, features);
    }

    public WebServerIService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVERISERVICE_QNAME);
    }

    public WebServerIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVERISERVICE_QNAME, features);
    }

    public WebServerIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServerIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServerI
     */
    @WebEndpoint(name = "WebServerIPort")
    public WebServerI getWebServerIPort() {
        return super.getPort(new QName("http://server.oukele.zh.com", "WebServerIPort"), WebServerI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServerI
     */
    @WebEndpoint(name = "WebServerIPort")
    public WebServerI getWebServerIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.oukele.zh.com", "WebServerIPort"), WebServerI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVERISERVICE_EXCEPTION!= null) {
            throw WEBSERVERISERVICE_EXCEPTION;
        }
        return WEBSERVERISERVICE_WSDL_LOCATION;
    }

}
