
package com.zh.oukele.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServerI", targetNamespace = "http://server.oukele.zh.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServerI {


    /**
     * 
     * @param visitId
     * @param id
     * @param visitSystem
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInfo", targetNamespace = "http://server.oukele.zh.com", className = "com.zh.oukele.server.GetInfo")
    @ResponseWrapper(localName = "getInfoResponse", targetNamespace = "http://server.oukele.zh.com", className = "com.zh.oukele.server.GetInfoResponse")
    public String getInfo(
        @WebParam(name = "visitSystem", targetNamespace = "")
        String visitSystem,
        @WebParam(name = "visitId", targetNamespace = "")
        String visitId,
        @WebParam(name = "id", targetNamespace = "")
        String id);

}
